//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int NovelId { get; set; }
        public int ChapterId { get; set; }
        public System.DateTime ReadTime { get; set; }
        public bool Hidden { get; set; }
    
        public virtual User User { get; set; }
        public virtual Novel Novel { get; set; }
        public virtual Chapter Chapter { get; set; }
    }
}
