<?xml version="1.0" encoding="utf-8"?><Database Class="NovelServerDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Users">
    <Type Name="User" />
  </Table>
</Database>