//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelServer
{
    using System;
    
    public enum NovelStatus : int
    {
        Active = 0,
        Inactive = 1,
        Completed = 2,
        Dropped = 3
    }
}
