//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerEntityContext : DbContext
    {
        public ServerEntityContext()
            : base("name=ServerEntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Novel> Novels { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<WebURL> WebURLs { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<ReadingList> ReadingLists { get; set; }
    }
}
