//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebURL
    {
        public int Id { get; set; }
        public int SourceId { get; set; }
        public int ChapterId { get; set; }
        public string Url { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Source Source { get; set; }
    }
}
